# Generated by Django 5.2.1 on 2025-05-21 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('work_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('buyer', models.CharField(max_length=64)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('sell_price', models.PositiveIntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
    ]
